python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 260     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.5    --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 420     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 245     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 450     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 250     --alpha_ECR 20     --weight_GR 2.1     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.4     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 460     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 225     --alpha_ECR 20     --weight_GR 2.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.01     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 450     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.4

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 210     --alpha_ECR 20     --weight_GR 1.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.3     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 405     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 220     --alpha_ECR 20     --weight_GR 2.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.01     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 460     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.65

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 230     --alpha_ECR 20     --weight_GR 2.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.2     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 420     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.55

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 225     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.3     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.05     --seed 211     --lr 0.002     --epochs 390     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.60

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 225     --alpha_ECR 19     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 410     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 235     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.1     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 400     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.3

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 230     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.2     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 400     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.72

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 210     --alpha_ECR 20     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.04     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 211     --lr 0.002     --epochs 470     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 270     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.2     --beta_temp 0.2     --dataset 20NG     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 211     --lr 0.002     --epochs 460     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.7