python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name MoCo     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 40     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 50     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset AGNews     --model NeuroMax     --num_topics 100     --dropout 0.0     --seed 60     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --init_2 0     --coef_ 2.5











