python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 55     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.5  

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 55     --alpha_ECR 21     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.75

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 60     --alpha_ECR 19     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.85

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 59     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 55     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 60     --alpha_ECR 21     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 66     --alpha_ECR 19     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.1

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 65     --alpha_ECR 18     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 54     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 52     --alpha_ECR 18.5     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 0.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 58     --alpha_ECR 21     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 56     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 63     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 70     --alpha_ECR 21     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 60     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 75     --alpha_ECR 19     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 1.05

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 57     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 55     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.9

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 62     --alpha_ECR 18     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 57     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 1.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 55     --alpha_ECR 17     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.9

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 60     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 58     --alpha_ECR 19     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 70     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12345     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 100     --alpha_ECR 18     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12346     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 0     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 60     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.2     --dataset YahooAnswers     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 12347     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name MGDA     --init_2 0   --learn 1     --coef_ 1.2










