python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 50     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 1.5     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.05     --seed 114     --lr 0.002     --epochs 200     --use_MOO 1     --MOO_name FairGrad     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 40     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 1.1     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.15     --seed 114     --lr 0.002     --epochs 305     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 60     --alpha_ECR 20     --weight_GR 2.1     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.01     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.10     --seed 114     --lr 0.002     --epochs 310     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 55     --alpha_ECR 20     --weight_GR 2.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 1.05     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 250     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 50     --alpha_ECR 20     --weight_GR 1.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 2.0     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 305     --use_MOO 1     --MOO_name FairGrad     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 50     --alpha_ECR 20     --weight_GR 2.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.9     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 260     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 70     --alpha_ECR 20     --weight_GR 2.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.5     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 320     --use_MOO 1     --MOO_name FairGrad     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 80     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 1.5     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.05     --seed 114     --lr 0.002     --epochs 290     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 60     --alpha_ECR 20     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 1.0     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.15     --seed 114     --lr 0.002     --epochs 310     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 70     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.7     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 300     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.4

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 80     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.4     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.05     --seed 114     --lr 0.002     --epochs 300     --use_MOO 1     --MOO_name FairGrad     --coef_ 2.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 60     --alpha_ECR 20     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.4     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.15     --seed 114     --lr 0.002     --epochs 270     --use_MOO 1     --MOO_name FairGrad     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 128     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 70     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.7     --beta_temp 0.2     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 114     --lr 0.002     --epochs 260     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.2