python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 180     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 185     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2.1     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.191     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 190     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 175     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.0     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 177     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 181     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 2.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 182     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 176     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 179     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 195     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.7     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.191     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 160     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.8     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.055     --beta_temp 0.189     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.0     --seed 115     --lr 0.0022     --epochs 165     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125 --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_ECR 65     --alpha_ECR 20     --weight_GR 1.5     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.05     --beta_temp 0.19     --dataset YahooAnswers     --model ECRTM     --num_topics 100     --dropout 0.00     --seed 115     --lr 0.0022     --epochs 170     --use_MOO 1     --MOO_name FairGrad     --coef_ 1.8