python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 15     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.5  

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 15     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 4.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 6     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 2.1

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 25     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.4     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.2     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 0.7

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 15     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 0.6

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.6     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 13     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 7     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 6     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 8     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 2.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 0.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.9

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 12     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5.7     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 1.2

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 4.5     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.9

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 6     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 10     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 1.5

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 7     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1331     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.0

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 8     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1332     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 0     --coef_ 0.8

python main.py     --num_groups 20     --device cuda     --lr_scheduler StepLR     --batch_size 200     --lr_step_size 125     --use_pretrainWE     --use_SAM 0     --SAM_name FSAM     --task_num 5     --use_decompose 1     --decompose_name Gram_Schmidt     --epoch_threshold -1     --weight_CL 0     --weight_ECR 6     --alpha_ECR 20     --weight_GR 2     --alpha_GR 5     --weight_InfoNCE 50     --weight_CTR 0.0     --beta_temp 0.1     --dataset AGNews     --model NeuroMax     --num_topics 50     --dropout 0.2     --seed 1333     --lr 0.002     --epochs 500     --use_MOO 1     --MOO_name PCGrad     --init_2 0   --learn 1     --coef_ 1.2










